# -*- coding: utf-8 -*-
"""Assignment12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzPo6iDlCYwjaZ20doYw6BEd_Q79MNVD

**1.sum all the items in a dictionary**
"""

dict={'a':4,'b':2,'c':3}
sum=0
for i in dict:
    sum += dict[i]
print("Sum:",sum)

"""**2.accessing an elements from a dictionary**"""

d={'a':4,'b':1,'c':3,'d':5,'e':0}
print(d['d'])
print(d)
d['f']=4
print(d)

"""**3.concate two dictionaries**"""

d1={'a':34,'b':24}
d2={'c':0,'d':1,'e':3}
d2.update(d1)
print("concate dictionary is:")
print(d2)

"""**4.add keys/values in a dictionary**"""

d={'a':4,'b':1,'c':3,'d':5,'e':0}
d['3']=0
d['a']='r'
print(d)

"""**5.the length of the dictionary**"""

d={'a':4,'b':1,'c':3,'d':5,'e':0}
print(len(d))

"""**6.remove items in the dictionary**"""

d={'a':4,'b':1,'c':3,'d':5,'e':0}
d.pop('e')
print(d)